### ISSUE TITLE
Absence de licence

### ISSUE THREAD

**Issue by scornec** [EPgg92/syllabise_py#1]
Bonjour,
Je suis en train de faire une thèse sur l'encodage de fichier XML autour du texte et de la musique, et dans ce cadre, votre projet m'intéresse car j'ai besoin de découper un texte en syllabes pour pouvoir le manipuler syllabe par syllabe après. Il n'y a pas de licence associée à votre projet, pourriez-vous peut-être en prendre une (GPL ou Apache) afin que je puisse utiliser votre code (en vous citant bien sûr) lors de mon projet de thèse ? Cela pourrait aussi permettre à d'autres personnes de contribuer à votre code (sans licence, c'est un peu délicat).
Merci,

**Comment by EPgg92** [comment]
done!
